//! Generate the docs-site pages for the HTTP problem types (`docs/agents/http-api-rules.md`).
//!
//! One page per [`ProblemType`] plus an index, under
//! `docs/src/content/docs/vault/developer/reference/errors/`, regenerated with
//! `cargo run -p message-vault-server -- dump-error-docs --output <dir>`.
//! Each problem's `type` URL is one of these pages, so the pages and the
//! registry ship together: a type without a page is a broken URL, and the
//! drift test below fails the build before that can happen.
//!
//! This sits beside [`crate::cli_docs`], which does the same job for the CLI
//! reference, and [`crate::openapi::write_openapi`] for the OpenAPI document.

use std::path::Path;

use crate::problem::{ERRORS_URL, ProblemType};

/// Where the pages live, relative to the repository root.
pub const PAGES_DIR: &str = "docs/src/content/docs/vault/developer/reference/errors";

const MARKER: &str = "<!-- generated by `message-vault-server dump-error-docs`; do not edit -->";

/// The status with its reason phrase, as the style guide spells it.
fn status_line(kind: ProblemType) -> String {
    let status = kind.status();
    format!(
        "{} {}",
        status.as_u16(),
        status.canonical_reason().unwrap_or_default()
    )
}

/// One type's page: frontmatter, the status and `type` URL, then the text.
#[must_use]
pub fn type_page(kind: ProblemType) -> String {
    format!(
        "---\ntitle: {title}\ndescription: \"`{status}` — `{slug}`\"\neditUrl: false\n---\n\n\
         {MARKER}\n\n\
         | | |\n|---|---|\n\
         | Status | `{status}` |\n\
         | Type | `{url}` |\n\n\
         {page}\n",
        title = kind.title(),
        status = status_line(kind),
        slug = kind.slug(),
        url = kind.url(),
        page = kind.page().trim(),
    )
}

/// The index: what a problem document is, then every type with its status.
#[must_use]
pub fn index_page() -> String {
    let mut rows = String::new();
    for kind in ProblemType::ALL {
        rows.push_str(&format!(
            "| [`{slug}`](./{slug}/) | `{status}` | {title} |\n",
            slug = kind.slug(),
            status = status_line(kind),
            title = kind.title(),
        ));
    }
    format!(
        "---\ntitle: HTTP problem types\ndescription: Every failure the vault answers, one page per type.\neditUrl: false\nsidebar:\n  order: 0\n---\n\n\
         {MARKER}\n\n\
         Every failure on the vault's `/v1` interface answers an [RFC 7807](https://www.rfc-editor.org/rfc/rfc7807) problem document, served as `application/problem+json`:\n\n\
         ```json\n\
         {{\n  \"type\": \"{ERRORS_URL}username-taken\",\n  \"title\": \"Username taken\",\n  \"status\": 409,\n  \"detail\": \"username already taken: alice\",\n  \"request_id\": \"3f2b1c0e-8d4a-4b6e-9f21-5c7d8e9a0b1c\"\n}}\n\
         ```\n\n\
         `type` is the address of one of the pages below, and a client that needs to know what went wrong compares its last segment. `title` is fixed per type; `detail` is one sentence about this occurrence. A `validation-failed` problem lists `errors`, every rule the request broke, in place of `detail`. `request_id` repeats the response's `x-request-id` header, which the vault's log carries on every line the request produced.\n\n\
         A `500 Internal Server Error` has no page: its `type` is `about:blank`, and its detail is a fixed sentence, because the cause is in the vault's log and not something a client can act on.\n\n\
         | Type | Status | Title |\n|---|---|---|\n{rows}",
    )
}

/// Every page, as `(file name, contents)`.
#[must_use]
pub fn pages() -> Vec<(String, String)> {
    let mut out = vec![("index.md".to_string(), index_page())];
    out.extend(
        ProblemType::ALL
            .iter()
            .map(|kind| (format!("{}.md", kind.slug()), type_page(*kind))),
    );
    out
}

/// Write every page into `dir`, or print them all to stdout when `dir` is
/// `None`, each under a line naming its file.
///
/// # Errors
///
/// Returns an error when the directory or a page cannot be written.
pub fn write_error_docs(dir: Option<&Path>) -> anyhow::Result<()> {
    match dir {
        None => {
            use std::io::Write;
            let mut out = std::io::stdout().lock();
            for (name, page) in pages() {
                writeln!(out, "<!-- file: {name} -->\n{page}")?;
            }
        }
        Some(dir) => {
            std::fs::create_dir_all(dir)
                .map_err(|e| anyhow::anyhow!("mkdir {}: {e}", dir.display()))?;
            for (name, page) in pages() {
                let path = dir.join(name);
                std::fs::write(&path, page.as_bytes())
                    .map_err(|e| anyhow::anyhow!("write {}: {e}", path.display()))?;
            }
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_page_carries_the_marker_and_its_type_url() {
        for kind in ProblemType::ALL {
            let page = type_page(kind);
            assert!(page.contains(MARKER), "{}", kind.slug());
            assert!(page.contains(&kind.url()), "{}", kind.slug());
            assert!(
                page.contains(&status_line(kind)),
                "{} lacks its status line",
                kind.slug()
            );
        }
        let index = index_page();
        for kind in ProblemType::ALL {
            assert!(index.contains(&format!("[`{}`]", kind.slug())));
        }
    }

    #[test]
    fn the_rate_limited_page_states_the_limit_and_the_window() {
        let page = type_page(ProblemType::RateLimited);
        assert!(page.contains(&format!(
            "more than {} attempts",
            crate::credentials::AUTH_RATE_MAX
        )));
        assert!(page.contains(&format!(
            "inside {} seconds",
            crate::credentials::AUTH_RATE_WINDOW.as_secs()
        )));
    }

    #[test]
    fn committed_pages_match_the_generator() {
        // The twin of `cli_docs::tests::committed_page_matches_the_generator`:
        // a type added or reworded without regenerating, or a hand edit past
        // the marker, fails here instead of publishing a stale page or a
        // `type` URL with nothing behind it.
        let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../..");
        let dir = root.join(PAGES_DIR);
        for (name, generated) in pages() {
            let path = dir.join(&name);
            let committed = std::fs::read_to_string(&path).unwrap_or_else(|e| {
                panic!(
                    "{}: {e}; run: cargo run -p message-vault-server -- dump-error-docs --output {PAGES_DIR}",
                    path.display()
                )
            });
            assert_eq!(
                generated.trim_end(),
                committed.trim_end(),
                "{name} drifted; run: cargo run -p message-vault-server -- dump-error-docs --output {PAGES_DIR}"
            );
        }
        let on_disk = std::fs::read_dir(&dir)
            .expect("errors dir")
            .filter_map(Result::ok)
            .map(|e| e.file_name().to_string_lossy().into_owned())
            .filter(|n| n.ends_with(".md"))
            .count();
        assert_eq!(
            on_disk,
            pages().len(),
            "a page on disk names no registered type; delete it"
        );
    }
}
