//! Generate the server's CLI reference page for the docs site.
//!
//! The page lives at
//! `docs/src/content/docs/docs/developer/reference/server-cli.md` and is
//! regenerated with
//! `cargo run -p message-crate-server -- dump-cli-docs --output <path>`.
//!
//! This sits beside [`crate::openapi::write_openapi`], which does the same job
//! for the OpenAPI document. Both write a generated artifact the docs site
//! commits, so both live in the crate whose definitions they read rather than
//! in a separate tool that would have to depend on this one.

use std::io::Write;
use std::path::Path;

/// Starlight frontmatter title for the generated page.
const TITLE: &str = "Server CLI";
/// Starlight frontmatter description for the generated page.
const DESCRIPTION: &str = "Cargo subcommands for import, dedupe, contacts, demo reset, and serve.";

/// Render the page: Starlight frontmatter plus the clap-generated body.
///
/// `editUrl: false` and the do-not-edit marker keep the docs site from
/// inviting hand edits that the next regeneration would overwrite.
fn render_page(command: &clap::Command) -> String {
    let body = clap_markdown::help_markdown_command(command);
    format!(
        "---\ntitle: {TITLE}\ndescription: {DESCRIPTION}\neditUrl: false\n---\n\n\
         <!-- generated by `message-crate-server dump-cli-docs`; do not edit -->\n\n{}\n",
        body.trim(),
    )
}

/// The markdown source of the server CLI reference page.
pub fn page_markdown() -> String {
    render_page(&crate::cli::clap_command())
}

/// Write the page to `path`, or to stdout when `path` is `None`.
///
/// # Errors
///
/// Returns an error when the file cannot be written.
pub fn write_cli_docs(path: Option<&Path>) -> anyhow::Result<()> {
    let page = page_markdown();
    match path {
        None => {
            let mut out = std::io::stdout().lock();
            out.write_all(page.as_bytes())?;
        }
        Some(p) => std::fs::write(p, page.as_bytes())
            .map_err(|e| anyhow::anyhow!("write {}: {e}", p.display()))?,
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn page_has_starlight_frontmatter_and_the_do_not_edit_marker() {
        let page = page_markdown();
        assert!(page.starts_with("---\n"));
        assert!(page.contains(&format!("title: {TITLE}")));
        assert!(page.contains(&format!("description: {DESCRIPTION}")));
        assert!(page.contains("editUrl: false"));
        assert!(page.contains("do not edit"));
    }

    #[test]
    fn page_documents_the_server_subcommands() {
        // The page is the only generated CLI reference left on the docs site,
        // so a body that lost its subcommands would publish an empty page
        // rather than fail.
        let page = page_markdown();
        for subcommand in ["serve", "import", "dump-openapi", "dump-cli-docs"] {
            assert!(page.contains(subcommand), "missing {subcommand}:\n{page}");
        }
    }

    #[test]
    fn committed_page_matches_the_generator() {
        // The twin of `openapi::tests::committed_openapi_matches_dump`. Both
        // guard a generated file the docs site commits: a clap change that
        // skipped the regeneration, or a hand edit past the do-not-edit
        // marker, fails here instead of publishing a stale page.
        let generated = page_markdown();
        let committed = include_str!(
            "../../../../docs/src/content/docs/docs/developer/reference/server-cli.md"
        );
        assert_eq!(
            generated.trim_end(),
            committed.trim_end(),
            "run: cargo run -p message-crate-server -- dump-cli-docs --output docs/src/content/docs/docs/developer/reference/server-cli.md"
        );
    }
}
