[package]
name = "go-sms-pro-exporter"
version = "0.1.0"
edition = "2024"
license = "LicenseRef-FCL-1.0-ALv2"
autotests = false

[dependencies]
anyhow = { workspace = true }
csv = "1.4.0"
hex = { workspace = true }
contacts = { path = "../../libs/contacts" }
go-sms-mms = { path = "../../libs/go-sms-mms" }
message-vault-io-core = { path = "../../core/message-vault-io-core" }
message-ir = { path = "../../libs/ir" }
message-ir-format = { path = "../../libs/ir-format" }
media = { path = "../../libs/media" }
phone = { path = "../../libs/phone" }
quick-xml = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }

[dev-dependencies]
message-vault-io-core = { path = "../../core/message-vault-io-core", features = ["testutil"] }
tempfile = { workspace = true }
