[package]
name = "message-reexport"
version = "0.1.0"
edition = "2024"
description = "Convert a Message Vault output directory to another format"
license = "LicenseRef-FCL-1.0-ALv2"

[dependencies]
anyhow = { workspace = true }
csv = "1.4.0"
message-vault-io-core = { path = "../../core/message-vault-io-core" }
message-ir = { path = "../ir" }
message-ir-format = { path = "../ir-format" }
media = { path = "../media" }
serde_json = { workspace = true }

[dev-dependencies]
message-ir = { path = "../ir", features = ["testutil"] }
tempfile = { workspace = true }
