#!/usr/bin/env node
/**
 * Copy the schema/sql/*.sql files listed in PARTS (all but saved_searches.sql)
 * into web-next/src/lib/vaultSchema.generated.ts.
 * Optionally refresh tests/fixtures/schema/current-schema.json from a fresh apply.
 *
 * Usage:
 *   node scripts/sync-schema.mjs
 *   node scripts/sync-schema.mjs --check
 */
import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const sqlDir = path.join(root, "schema", "sql");
const generatedPath = path.join(
  root,
  "web-next",
  "src",
  "lib",
  "vaultSchema.generated.ts",
);
const fixturePath = path.join(
  root,
  "tests",
  "fixtures",
  "schema",
  "current-schema.json",
);

/** @type {Array<{ file: string, exportName: string }>} */
const PARTS = [
  { file: "accounts.sql", exportName: "ACCOUNTS_DDL" },
  { file: "messages.sql", exportName: "MESSAGES_DDL" },
  { file: "staging.sql", exportName: "STAGING_DDL" },
  { file: "contacts.sql", exportName: "CONTACTS_DDL" },
  { file: "fts_virtual.sql", exportName: "FTS_VIRTUAL_DDL" },
  { file: "fts_triggers_drop.sql", exportName: "FTS_TRIGGERS_DROP_SQL" },
  { file: "fts_triggers_create.sql", exportName: "FTS_TRIGGERS_CREATE_SQL" },
];

const checkOnly = process.argv.includes("--check");

function escapeForTemplateLiteral(sql) {
  return sql.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

function buildGeneratedTs() {
  const chunks = [
    "// DO NOT EDIT — generated by scripts/sync-schema.mjs",
    "// Source: schema/sql/*.sql",
    "",
  ];
  for (const { file, exportName } of PARTS) {
    const sql = fs.readFileSync(path.join(sqlDir, file), "utf8");
    chunks.push(
      `export const ${exportName} = \`${escapeForTemplateLiteral(sql)}\`;`,
      "",
    );
  }
  return chunks.join("\n");
}

function writeIfChanged(filePath, contents) {
  const prev = fs.existsSync(filePath)
    ? fs.readFileSync(filePath, "utf8")
    : null;
  if (prev === contents) {
    return false;
  }
  if (checkOnly) {
    return true;
  }
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, contents, "utf8");
  return true;
}

function refreshFixture() {
  const require = createRequire(import.meta.url);
  let Database;
  try {
    Database = require(
      path.join(root, "web-next", "node_modules", "better-sqlite3"),
    );
  } catch {
    console.warn(
      "sync-schema: better-sqlite3 not found under web-next/; skipping fixture refresh",
    );
    return false;
  }

  const db = new Database(":memory:");
  db.pragma("foreign_keys = ON");
  for (const { file } of PARTS.slice(0, 4)) {
    db.exec(fs.readFileSync(path.join(sqlDir, file), "utf8"));
  }
  db.exec(fs.readFileSync(path.join(sqlDir, "fts_virtual.sql"), "utf8"));
  db.exec(fs.readFileSync(path.join(sqlDir, "fts_triggers_drop.sql"), "utf8"));
  db.exec(fs.readFileSync(path.join(sqlDir, "fts_triggers_create.sql"), "utf8"));
  db.prepare(
    `INSERT OR REPLACE INTO schema_meta (key, value) VALUES (?, '1')`,
  ).run("messages_fts_triggers_v1");

  const names = (type) =>
    db
      .prepare(
        `SELECT name FROM sqlite_master WHERE type = ? AND name NOT LIKE 'sqlite_%' ORDER BY name`,
      )
      .all(type)
      .map((row) => row.name);

  const metaKeys = () =>
    db
      .prepare(`SELECT key FROM schema_meta ORDER BY key`)
      .all()
      .map((row) => row.key);

  // Preserve fixture order from the previous contract when possible.
  const previous = JSON.parse(fs.readFileSync(fixturePath, "utf8"));
  const bySet = (wanted, actual) => {
    const set = new Set(actual);
    const ordered = wanted.filter((name) => set.has(name));
    for (const name of actual) {
      if (!ordered.includes(name)) ordered.push(name);
    }
    return ordered;
  };

  // Keep the virtual FTS table; skip SQLite FTS5 shadow tables.
  const tables = names("table").filter(
    (name) => name === "messages_fts" || !name.startsWith("messages_fts_"),
  );

  const next = {
    tables: bySet(previous.tables, tables),
    indexes: bySet(
      previous.indexes,
      names("index").filter((n) => !n.startsWith("sqlite_")),
    ),
    triggers: bySet(previous.triggers, names("trigger")),
    metadata: bySet(previous.metadata, metaKeys()),
  };
  db.close();

  const contents = `${JSON.stringify(next, null, 2)}\n`;
  return writeIfChanged(fixturePath, contents);
}

const generated = buildGeneratedTs();
const genChanged = writeIfChanged(generatedPath, generated);
const fixtureChanged = refreshFixture();

if (checkOnly) {
  if (genChanged || fixtureChanged) {
    console.error(
      "sync-schema: generated outputs are out of date. Run: node scripts/sync-schema.mjs",
    );
    process.exit(1);
  }
  console.log("sync-schema: OK (no changes)");
  process.exit(0);
}

const notes = [];
if (genChanged) notes.push(path.relative(root, generatedPath));
if (fixtureChanged) notes.push(path.relative(root, fixturePath));
if (notes.length === 0) {
  console.log("sync-schema: already up to date");
} else {
  console.log(`sync-schema: wrote ${notes.join(", ")}`);
}
